apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.authproviderbearer.cfgmapName }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
data:
  revad.toml: |-
    [shared]
    gatewaysvc = "{{ .Release.Name }}-gateway:9142"
    jwt_secret = "POZSOrlP7AgnTxH7MJebWV8ohvsApgbd4u3Joen30c"

    [grpc]
    address = "0.0.0.0:9158"

    [grpc.services.authprovider]
    auth_manager = "oidc"

    [grpc.services.authprovider.auth_managers.oidc]
    insecure = {{ .Values.authproviderbearer.oidc.insecure }}
    issuer = {{ quote .Values.authproviderbearer.oidc.issuer }}
    id_claim = {{ quote .Values.authproviderbearer.oidc.id_claim }}
    uid_claim = {{ quote .Values.authproviderbearer.oidc.uid_claim }}
    gid_claim = {{ quote .Values.authproviderbearer.oidc.gid_claim }}
    gatewaysvc = "{{ .Release.Name }}-gateway:9142"
