apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocis.fullname" . }}-configfiles
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
data:
{{- if .Values.configFiles }}
{{- range $filename, $fileContents := .Values.configFiles }}
  {{ $filename }}: |-
{{ $fileContents | indent 4 }}
{{- end }}
{{- end }}
