apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocis.fullname" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ocis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ocis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        {{- $chart := .Chart -}}
        {{- $values := .Values -}}
        {{- range .Values.extensions }}
        - name: "{{ $chart.Name }}-{{ . }}"
          image: "{{ $values.image.repository }}:{{ $values.image.tag }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          command: ["/usr/bin/ocis", "{{ . }}"]
          env:
          {{- range $name, $value := $values.env }}
            - name: "{{ $name }}"
              value: "{{ $value }}"
          {{- end }}
          {{- if $values.extraEnv }}
            {{- toYaml $values.extraEnv | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: ocis-configfiles
              mountPath: /etc/ocis/
            - name: ocis-data
              mountPath: "{{ $values.persistentVolume.mountPath }}"
              subPath: "{{ $values.persistentVolume.subPath }}"
          resources:
            {{- toYaml $values.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: ocis-configfiles
          configMap:
            name: {{ include "ocis.fullname" . }}-configfiles
            defaultMode: 0777
        - name: ocis-data
        {{- if .Values.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistentVolume.existingClaim }}{{ .Values.persistentVolume.existingClaim }}{{- else }}{{ template "ocis.fullname" . }}{{- end }}
        {{- else }}
          emptyDir:
          {{- if .Values.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.emptyDir.sizeLimit }}
          {{- else }}
            {}
          {{- end -}}
        {{- end -}}
