{{- if .Values.services }}
{{ $services := omit .Values.services "type" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocis.fullname" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.type }}
  {{- $services := omit .Values.services "type" }}
  ports:
{{- range $service, $properties := $services }}
    - port: {{ $properties.port }}
      targetPort: {{ $properties.targetPort | default $properties.port}}
      protocol: {{ $properties.protocol | default "TCP" }}
      name: {{ $service }}
{{- end }}
  selector:
    {{- include "ocis.selectorLabels" . | nindent 4 }}
{{- end }}
