#
# CERNBox chart for use with ScienceBox
#

#
# CERNBox web interface with custom web assets and theme served by nginx
cernbox-web:
  initContainers:
    - name: cernbox-web-init
      # -- image that the initContainer should use
      image: busybox
      # -- Command that the initContainer runs after startup
      command: ["/bin/sh", "/root/cbox_init.sh"]
      # -- Environment Variables
      env:
        # -- URL for the cernbox web asset tarball
      - name: WEB_ASSET
        # -- value for the web-asset env var
        value: https://github.com/cernbox/web-release/releases/download/v0.0.9/web.tar.gz
        # -- URL for the cernbox theme tarball
      - name: WEB_THEME
        # -- value for the web-theme env var
        value: https://github.com/cernbox/web-extensions/releases/download/theme-cernbox/v0.1.7/theme-cernbox.tar.gz
      # -- volume mount for the initContainer
      volumeMounts:
        # -- web-init volume mount to mount the init shell script onto the initContainer
      - name: web-init
        # -- web-init volume mount path
        mountPath: /root/cbox_init.sh
        subPath: cbox_init.sh
        # -- web-content mount to mount the web content
      - name: web-content
        # -- web-content volume mount path
        mountPath: /var/www/web/
  extraVolumeMounts:
    - name: web-nginx
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: web-config
      mountPath: /var/www/web/config.json
      subPath: config.json
    - name: web-content
      mountPath: /var/www/web/
  extraVolumes:
    - name: web-nginx
      configMap:
        name: cernbox-web-nginx
    - name: web-config
      configMap:
        name: cernbox-web-config
    - name: web-init
      configMap:
        name: cernbox-web-init
        defaultMode: 0755
    - name: web-content
      emptyDir: {}
  command: ["/opt/bitnami/nginx/sbin/nginx"]
  args: ["-c", "/etc/nginx/nginx.conf"]
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

#
# CERNBox web config: Extra values to populate configMaps used by cernbox-web
web:
  oidcClientId: "web"
  oidcScope: "openid profile email"

#
# oCIS proxy and IDP extensions
ocis:
  image:
    # -- image to use for deploying ocis
    repository: gitlab-registry.cern.ch/sciencebox/docker-images/ocis
    # -- image tag to use
    tag: 1.20.0
  # -- ocis extensions (https://owncloud.dev/services/)
  extensions:
    - proxy
    - idp
  env:
    # -- IDP Config - https://owncloud.dev/services/idp/configuration/#environment-variables
    IDP_ACCESS_TOKEN_EXPIRATION: 28800
    # -- IDP issuer URL
    IDP_ISS: https://sciencebox.local
    # -- set insecure flag for the idp
    IDP_INSECURE: true
    # -- Port on which the IDP listens
    IDP_HTTP_ADDR: 0.0.0.0:9130
    # -- Reva Gateway address (Cernbox backend)
    REVA_GATEWAY: sciencebox-gateway.default.svc.cluster.local:9142
    # -- LDAP URI address
    LDAP_URI: ldaps://sciencebox-ldap:636
    # -- set insecure flag for the LDAP
    LDAP_INSECURE: true
    # -- LDAP - Bind DN
    LDAP_BIND_DN: "cn=readuser,dc=owncloud,dc=com"
    # -- LDAP - Bind password
    LDAP_BIND_PASSWORD: readuser
    # -- LDAP - group base dn
    LDAP_GROUP_BASE_DN: "dc=owncloud,dc=com"
    # -- LDAP - group filter
    LDAP_GROUPFILTER: "(objectclass=owncloud)"
    # -- LDAP - group object class
    LDAP_GROUP_OBJECTCLASS: "groupOfUniqueNames"
    # -- LDAP - user base dn
    LDAP_USER_BASE_DN: "dc=owncloud,dc=com"
    # -- LDAP - user filter
    LDAP_USERFILTER: "(objectclass=owncloud)"
    # -- LDAP - user object class
    LDAP_USER_OBEJECTCLASS: "inetOrgPerson"
    # -- LDAP - Login attributes
    LDAP_LOGIN_ATTRIBUTES: "uid,mail"
    IDP_LDAP_LOGIN_ATTRIBUTE: "uid"
    IDP_LDAP_UUID_ATTRIBUTE: "ownclouduuid"
    IDP_LDAP_UUID_ATTRIBUTE_TYPE: binary

    # -- Proxy Config - https://owncloud.dev/services/proxy/configuration/
    PROXY_ACCOUNT_BACKEND_TYPE: cs3
    OCIS_LOG_LEVEL: debug
    PROXY_TLS: true
    OCIS_JWT_SECRET: Pive-Fumkiu4
    STORAGE_TRANSFER_SECRET: replace-me-with-a-transfer-secret
    OCIS_MACHINE_AUTH_API_KEY: random_api_key
    OCIS_INSECURE: true
    PROXY_ENABLE_BASIC_AUTH: false
    ACCOUNTS_DEMO_USERS_AND_GROUPS: false
    IDM_CREATE_DEMO_USERS: false
  ingress:
    # -- enable ingress for ocis
    enabled: true
    # -- expose the IDP via the ingress
    exposeIdp: true
    # -- ingress annotation
    annotation:
      "nginx.ingress.kubernetes.io/backend-protocol": "HTTPS"


## Revad Configurations

#
# revad gateway
gateway:
  image:
    # -- gateway image to use for deployment
    repository: cs3org/revad
    # -- image tag to use
    tag: v1.19.0
  env:
    # -- XrdSecPROTOCOL - protocol used to authenticate against EOS
    XrdSecPROTOCOL: sss
  # -- configMap containing revad gateway TOML configurations
  cfgmapName: gateway-config
  # -- revad gateway service configuration
  service:
    # -- grpc port
    grpc:
      # -- port that gateway grpc service listens on
      port: 9142
    # -- http port
    http:
      # -- port that gateway http service listens on
      port: 9143

#
# revad storageprovider home
storageproviderhome:
  image:
    # -- storageproviderhome image to use for deployment
    repository: &revadStorageproviderImageRepo cs3org/revad
    # -- image tag to use
    tag: &revadStorageproviderImageTag v1.19.0-eos
  env:
    # -- XrdSecPROTOCOL - protocol used to authenticate against EOS
    XrdSecPROTOCOL: sss
  # --configMap containing revad storageproviderhome TOML configurations
  cfgmapName: storageprovider-home-config
  # -- service configurations
  service:
    # -- grpc port
    grpc:
      # -- port that grpc service listens on
      port: 18000
    # -- http port
    http:
      # -- port that http service listens on
      port: 17000

#
# revad storageprovider public
storageproviderpublic:
  image:
    # -- storageproviderpublic image to use for deployment
    repository: *revadStorageproviderImageRepo
    # -- image tag to use
    tag: *revadStorageproviderImageTag
  env:
    # -- XrdSecPROTOCOL - protocol used to authenticate against EOS
    XrdSecPROTOCOL: sss
  # --configMap containing revad storageproviderpublic TOML configurations
  cfgmapName: storageprovider-public-config
  # -- service configurations
  service:
    # -- grpc port
    grpc:
      # -- port the grpc service listens on
      port: 9278

#
# revad storageprovider user
storageprovideruser:
  image:
    # -- storageprovideruser image to use for deployment
    repository: *revadStorageproviderImageRepo
    # -- image tag to use
    tag: *revadStorageproviderImageTag
  env:
    # -- XrdSecPROTOCOL - protocol used to authenticate against EOS
    XrdSecPROTOCOL: sss
  # --configMap containing revad storageprovideruser TOML configurations
  cfgmapName: storageprovider-user-config
  service:
    grpc:
      # -- port the grpc service listens on
      port: 16000
    http:
      # -- port the http service listens on
      port: 15000

#
# revad authprovider machine
authprovidermachine:
  image:
    repository: &revadAuthproviderImageRepo ghcr.io/cernbox/reva
    tag: &revadAuthproviderImageTag cernbox
  cfgmapName: authprovider-machine-config
  service:
    grpc:
      port: 9166

#
# revad authprovider bearer
authproviderbearer:
  image:
    # -- authproviderbearer image to use for deployment
    repository: *revadAuthproviderImageRepo
    # -- image tag to use
    tag: *revadAuthproviderImageTag
  # -- cfgmap containing revad authprovider bearer TOML configuratinos
  cfgmapName: authprovider-bearer-config
  oidc:
    insecure: true
    id_claim: name
    uid_claim: uid
    gid_claim: gid
  service:
    grpc:
      # -- port the grpc service listens on
      port: 9158
