gateway:
  image:
    repository: cs3org/revad
    tag: v1.19.0
  cfgmapName: gateway-config

storageproviderhome:
  image:
    repository: cs3org/revad
    tag: v1.19.0-eos
  cfgmapName: storageprovider-home-config

storageproviderpublic:
  image:
    repository: cs3org/revad
    tag: v1.19.0-eos
  cfgmapName: storageprovider-public-config

storageprovideruser:
  image:
    repository: cs3org/revad
    tag: v1.19.0-eos
  cfgmapName: storageprovider-user-config

authprovidermachine:
  image:
    repository: gitlab-registry.cern.ch/sciencebox/hotfixes/revad
    tag: latest-20220815
  cfgmapName: authprovider-machine-config

authproviderbearer:
  image:
    repository: gitlab-registry.cern.ch/sciencebox/hotfixes/revad
    tag: latest-20220815
  cfgmapName: authprovider-bearer-config
