---
"$schema": http://json-schema.org/schema
type: object
required:
- image
- repositories
properties:
  image:
    type: object
    required:
    - repository
    - tag
    - pullPolicy
    properties:
      repository:
        type: string
        pattern: "^[.a-z0-9-_/]+$"
      pullPolicy:
        type: string
        enum:
        - Always
        - Never
        - IfNotPresent
      tag:
        type: string
  podAssignment:
    type: object
    properties:
      enableNodeSelector:
        type: boolean
  customLabels:
    type: object
    properties:
      service:
        type: string
      component:
        type: string
  repositories:
    type: array
    items:
      type: string
  default_local:
    type: object
    properties:
      CVMFS_DNS_MIN_TTL:
        type: integer
      CVMFS_QUOTA_LIMIT:
        type: integer
      CVMFS_HTTP_PROXY:
        type: string
      CVMFS_CACHE_BASE:
        type: string
      CVMFS_PROXY_SHARD:
        type: boolean
  mountOptions:
    type: object
    properties:
      uid:
        type: integer
      gid:
        type: integer
      hostMountpoint:
        type: string
  prefetcher:
    type: object
    properties:
      enabled:
        type: boolean
  deployDaemonSet:
    type: boolean
  deployCsiDriver:
    type: boolean
  useCsiDriver:
    type: boolean
