apiVersion: v2
#
name: sciencebox
type: application
version: 0.0.8
#
description: The chart to deploy and configure ScienceBox

dependencies:
#
# User account info
- name: openldap
  alias: ldap
  version: 2.0.4
  repository: "https://jp-gouin.github.io/helm-openldap/"
- name: ldap-instance-config
  version: 0.0.1
  repository: "oci://registry.cern.ch/sciencebox/charts"
#
# CBox shares
- name: mariadb
  version: 11.4.2
  repository: "https://charts.bitnami.com/bitnami"
#
# ScienceBox welcome page
- name: nginx
  alias: nginx-welcome-page
  version: 13.2.19
  repository: "https://charts.bitnami.com/bitnami"
#
# EOS
- name: server
  alias: eos
  version: 0.1.5
  repository: "oci://registry.cern.ch/eos/charts"
- name: eos-instance-config
  version: 0.0.6
  repository: "oci://registry.cern.ch/sciencebox/charts"
- name: eos-user-cache-refresher
  version: 0.0.2
  repository: "oci://registry.cern.ch/sciencebox/charts"
#
# SWAN
- name: swan
  version: 0.1.11
  repository: "oci://registry.cern.ch/swan/charts"
#
# CERNBox
- name: cernbox
  version: 0.0.5
  repository: "oci://registry.cern.ch/sciencebox/charts"
